// source: msg.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.ws.P_BASE', null, global);
goog.exportSymbol('proto.ws.P_DISPLACE', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ws.P_DISPLACE = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ws.P_DISPLACE, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ws.P_DISPLACE.displayName = 'proto.ws.P_DISPLACE';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ws.P_DISPLACE.prototype.toObject = function(opt_includeInstance) {
  return proto.ws.P_DISPLACE.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ws.P_DISPLACE} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ws.P_DISPLACE.toObject = function(includeInstance, msg) {
  var f, obj = {
    oldIp: msg.getOldIp_asB64(),
    newIp: msg.getNewIp_asB64(),
    ts: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ws.P_DISPLACE}
 */
proto.ws.P_DISPLACE.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ws.P_DISPLACE;
  return proto.ws.P_DISPLACE.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ws.P_DISPLACE} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ws.P_DISPLACE}
 */
proto.ws.P_DISPLACE.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setOldIp(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setNewIp(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ws.P_DISPLACE.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ws.P_DISPLACE.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ws.P_DISPLACE} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ws.P_DISPLACE.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOldIp_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getNewIp_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getTs();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
};


/**
 * optional bytes old_ip = 1;
 * @return {!(string|Uint8Array)}
 */
proto.ws.P_DISPLACE.prototype.getOldIp = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes old_ip = 1;
 * This is a type-conversion wrapper around `getOldIp()`
 * @return {string}
 */
proto.ws.P_DISPLACE.prototype.getOldIp_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getOldIp()));
};


/**
 * optional bytes old_ip = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getOldIp()`
 * @return {!Uint8Array}
 */
proto.ws.P_DISPLACE.prototype.getOldIp_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getOldIp()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.ws.P_DISPLACE} returns this
 */
proto.ws.P_DISPLACE.prototype.setOldIp = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional bytes new_ip = 2;
 * @return {!(string|Uint8Array)}
 */
proto.ws.P_DISPLACE.prototype.getNewIp = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes new_ip = 2;
 * This is a type-conversion wrapper around `getNewIp()`
 * @return {string}
 */
proto.ws.P_DISPLACE.prototype.getNewIp_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getNewIp()));
};


/**
 * optional bytes new_ip = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getNewIp()`
 * @return {!Uint8Array}
 */
proto.ws.P_DISPLACE.prototype.getNewIp_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getNewIp()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.ws.P_DISPLACE} returns this
 */
proto.ws.P_DISPLACE.prototype.setNewIp = function(value) {
  return jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * optional int64 ts = 3;
 * @return {number}
 */
proto.ws.P_DISPLACE.prototype.getTs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.ws.P_DISPLACE} returns this
 */
proto.ws.P_DISPLACE.prototype.setTs = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * @enum {number}
 */
proto.ws.P_BASE = {
  NONE: 0,
  S2C_ERR_DISPLACE: 2147483647
};

goog.object.extend(exports, proto.ws);
