// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: ws/msg.proto

package ws

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//基础协议
type P_S2C int32

const (
	P_S2C_s2c_connected    P_S2C = 0 //连接成功建立
	P_S2C_s2c_err_displace P_S2C = 1 //被顶号
)

// Enum value maps for P_S2C.
var (
	P_S2C_name = map[int32]string{
		0: "s2c_connected",
		1: "s2c_err_displace",
	}
	P_S2C_value = map[string]int32{
		"s2c_connected":    0,
		"s2c_err_displace": 1,
	}
)

func (x P_S2C) Enum() *P_S2C {
	p := new(P_S2C)
	*p = x
	return p
}

func (x P_S2C) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (P_S2C) Descriptor() protoreflect.EnumDescriptor {
	return file_ws_msg_proto_enumTypes[0].Descriptor()
}

func (P_S2C) Type() protoreflect.EnumType {
	return &file_ws_msg_proto_enumTypes[0]
}

func (x P_S2C) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use P_S2C.Descriptor instead.
func (P_S2C) EnumDescriptor() ([]byte, []int) {
	return file_ws_msg_proto_rawDescGZIP(), []int{0}
}

//通用消息体封装
type P_MESSAGE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProtocolId int32  `protobuf:"varint,1,opt,name=protocol_id,json=protocolId,proto3" json:"protocol_id,omitempty"` //消息协议ID
	Data       []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                                //内容-自定义消息
}

func (x *P_MESSAGE) Reset() {
	*x = P_MESSAGE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ws_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *P_MESSAGE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P_MESSAGE) ProtoMessage() {}

func (x *P_MESSAGE) ProtoReflect() protoreflect.Message {
	mi := &file_ws_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P_MESSAGE.ProtoReflect.Descriptor instead.
func (*P_MESSAGE) Descriptor() ([]byte, []int) {
	return file_ws_msg_proto_rawDescGZIP(), []int{0}
}

func (x *P_MESSAGE) GetProtocolId() int32 {
	if x != nil {
		return x.ProtocolId
	}
	return 0
}

func (x *P_MESSAGE) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_ws_msg_proto protoreflect.FileDescriptor

var file_ws_msg_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x77, 0x73, 0x2f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x77, 0x73, 0x22, 0x40, 0x0a, 0x09, 0x50, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x12,
	0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x2a, 0x30, 0x0a, 0x05, 0x50, 0x5f, 0x53, 0x32, 0x43, 0x12, 0x11, 0x0a,
	0x0d, 0x73, 0x32, 0x63, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x10, 0x00,
	0x12, 0x14, 0x0a, 0x10, 0x73, 0x32, 0x63, 0x5f, 0x65, 0x72, 0x72, 0x5f, 0x64, 0x69, 0x73, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x10, 0x01, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x77, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ws_msg_proto_rawDescOnce sync.Once
	file_ws_msg_proto_rawDescData = file_ws_msg_proto_rawDesc
)

func file_ws_msg_proto_rawDescGZIP() []byte {
	file_ws_msg_proto_rawDescOnce.Do(func() {
		file_ws_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_ws_msg_proto_rawDescData)
	})
	return file_ws_msg_proto_rawDescData
}

var file_ws_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ws_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ws_msg_proto_goTypes = []interface{}{
	(P_S2C)(0),        // 0: ws.P_S2C
	(*P_MESSAGE)(nil), // 1: ws.P_MESSAGE
}
var file_ws_msg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ws_msg_proto_init() }
func file_ws_msg_proto_init() {
	if File_ws_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ws_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*P_MESSAGE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ws_msg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ws_msg_proto_goTypes,
		DependencyIndexes: file_ws_msg_proto_depIdxs,
		EnumInfos:         file_ws_msg_proto_enumTypes,
		MessageInfos:      file_ws_msg_proto_msgTypes,
	}.Build()
	File_ws_msg_proto = out.File
	file_ws_msg_proto_rawDesc = nil
	file_ws_msg_proto_goTypes = nil
	file_ws_msg_proto_depIdxs = nil
}
