// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

#include "msg.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace ws {
PROTOBUF_CONSTEXPR P_DISPLACE::P_DISPLACE(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.old_ip_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.new_ip_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.ts_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct P_DISPLACEDefaultTypeInternal {
  PROTOBUF_CONSTEXPR P_DISPLACEDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~P_DISPLACEDefaultTypeInternal() {}
  union {
    P_DISPLACE _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 P_DISPLACEDefaultTypeInternal _P_DISPLACE_default_instance_;
}  // namespace ws
static ::_pb::Metadata file_level_metadata_msg_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_msg_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_msg_2eproto = nullptr;

const uint32_t TableStruct_msg_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ws::P_DISPLACE, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ws::P_DISPLACE, _impl_.old_ip_),
  PROTOBUF_FIELD_OFFSET(::ws::P_DISPLACE, _impl_.new_ip_),
  PROTOBUF_FIELD_OFFSET(::ws::P_DISPLACE, _impl_.ts_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::ws::P_DISPLACE)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::ws::_P_DISPLACE_default_instance_._instance,
};

const char descriptor_table_protodef_msg_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\tmsg.proto\022\002ws\"8\n\nP_DISPLACE\022\016\n\006old_ip\030"
  "\001 \001(\014\022\016\n\006new_ip\030\002 \001(\014\022\n\n\002ts\030\003 \001(\003*,\n\006P_B"
  "ASE\022\010\n\004none\020\000\022\030\n\020s2c_err_displace\020\377\377\377\377\007B"
  "\005Z\003/wsb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_msg_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_msg_2eproto = {
    false, false, 134, descriptor_table_protodef_msg_2eproto,
    "msg.proto",
    &descriptor_table_msg_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_msg_2eproto::offsets,
    file_level_metadata_msg_2eproto, file_level_enum_descriptors_msg_2eproto,
    file_level_service_descriptors_msg_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_msg_2eproto_getter() {
  return &descriptor_table_msg_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_msg_2eproto(&descriptor_table_msg_2eproto);
namespace ws {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* P_BASE_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_msg_2eproto);
  return file_level_enum_descriptors_msg_2eproto[0];
}
bool P_BASE_IsValid(int value) {
  switch (value) {
    case 0:
    case 2147483647:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class P_DISPLACE::_Internal {
 public:
};

P_DISPLACE::P_DISPLACE(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ws.P_DISPLACE)
}
P_DISPLACE::P_DISPLACE(const P_DISPLACE& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  P_DISPLACE* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.old_ip_){}
    , decltype(_impl_.new_ip_){}
    , decltype(_impl_.ts_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.old_ip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.old_ip_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_old_ip().empty()) {
    _this->_impl_.old_ip_.Set(from._internal_old_ip(), 
      _this->GetArenaForAllocation());
  }
  _impl_.new_ip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.new_ip_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_new_ip().empty()) {
    _this->_impl_.new_ip_.Set(from._internal_new_ip(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.ts_ = from._impl_.ts_;
  // @@protoc_insertion_point(copy_constructor:ws.P_DISPLACE)
}

inline void P_DISPLACE::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.old_ip_){}
    , decltype(_impl_.new_ip_){}
    , decltype(_impl_.ts_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.old_ip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.old_ip_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.new_ip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.new_ip_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

P_DISPLACE::~P_DISPLACE() {
  // @@protoc_insertion_point(destructor:ws.P_DISPLACE)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void P_DISPLACE::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.old_ip_.Destroy();
  _impl_.new_ip_.Destroy();
}

void P_DISPLACE::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void P_DISPLACE::Clear() {
// @@protoc_insertion_point(message_clear_start:ws.P_DISPLACE)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.old_ip_.ClearToEmpty();
  _impl_.new_ip_.ClearToEmpty();
  _impl_.ts_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* P_DISPLACE::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes old_ip = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_old_ip();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes new_ip = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_new_ip();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 ts = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.ts_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* P_DISPLACE::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ws.P_DISPLACE)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes old_ip = 1;
  if (!this->_internal_old_ip().empty()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_old_ip(), target);
  }

  // bytes new_ip = 2;
  if (!this->_internal_new_ip().empty()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_new_ip(), target);
  }

  // int64 ts = 3;
  if (this->_internal_ts() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(3, this->_internal_ts(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ws.P_DISPLACE)
  return target;
}

size_t P_DISPLACE::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ws.P_DISPLACE)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes old_ip = 1;
  if (!this->_internal_old_ip().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_old_ip());
  }

  // bytes new_ip = 2;
  if (!this->_internal_new_ip().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_new_ip());
  }

  // int64 ts = 3;
  if (this->_internal_ts() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_ts());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData P_DISPLACE::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    P_DISPLACE::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*P_DISPLACE::GetClassData() const { return &_class_data_; }


void P_DISPLACE::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<P_DISPLACE*>(&to_msg);
  auto& from = static_cast<const P_DISPLACE&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ws.P_DISPLACE)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_old_ip().empty()) {
    _this->_internal_set_old_ip(from._internal_old_ip());
  }
  if (!from._internal_new_ip().empty()) {
    _this->_internal_set_new_ip(from._internal_new_ip());
  }
  if (from._internal_ts() != 0) {
    _this->_internal_set_ts(from._internal_ts());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void P_DISPLACE::CopyFrom(const P_DISPLACE& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ws.P_DISPLACE)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool P_DISPLACE::IsInitialized() const {
  return true;
}

void P_DISPLACE::InternalSwap(P_DISPLACE* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.old_ip_, lhs_arena,
      &other->_impl_.old_ip_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.new_ip_, lhs_arena,
      &other->_impl_.new_ip_, rhs_arena
  );
  swap(_impl_.ts_, other->_impl_.ts_);
}

::PROTOBUF_NAMESPACE_ID::Metadata P_DISPLACE::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_msg_2eproto_getter, &descriptor_table_msg_2eproto_once,
      file_level_metadata_msg_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace ws
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ws::P_DISPLACE*
Arena::CreateMaybeMessage< ::ws::P_DISPLACE >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ws::P_DISPLACE >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
